name: NodeJS with Gulp

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Build with Gulp
        run: npx gulp

      - name: Copy dist contents to root
        run: cp -r dist/* $GITHUB_WORKSPACE/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: List current working directory
        run: ls -l

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./dist
          external_repository: nashidahmed/nashidahmed.github.io
